apiVersion: ngrok.k8s.ngrok.com/v1alpha1
kind: NgrokTrafficPolicy
metadata:
  labels:
    app.kubernetes.io/name: ngroktrafficpolicy
    app.kubernetes.io/instance: ngroktrafficpolicy-sample
    app.kubernetes.io/part-of: kubernetes-ingress-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubernetes-ingress-controller
  name: ngroktrafficpolicy-sample
spec:
  # TODO(user): Add fields here
