name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: debianmaster/actions-k3s@master
      id: k3s
      with:
        version: 'latest'
    - run: |
        kubectl get nodes
        kubectl get pods -A

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19 # Use the latest

    - name: Build
      run: make build

    - name: Test and Lint
      run: make test

    - name: Build the Docker image
      run: make docker-build

    - name: Deploy controller to local cluster
      run: make deploy

    - name: Check if controller is up
      run: |
        kubectl get nodes
        kubectl get pods -A

  helm:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v3
    - uses: azure/setup-helm@v3
      with:
        version: v3.10.0
    - name: Lint Helm Chart
      run: make helm-lint
    - name: Helm Unit Tests
      run: make helm-test
