name: Docker

on:
  push:
    branches:
      - main

env:
  DOCKER_BUILDX_PLATFORMS: linux/amd64,linux/arm64

jobs:
  release:
    name: Release Images
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: |
      github.repository == 'ngrok/ngrok-ingress-controller' &&
      github.event_name == 'push' &&
      github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - id: buildx-setup
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: ${{ env.DOCKER_BUILDX_PLATFORMS }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: ${{ steps.buildx-setup.outputs.platforms }}
          push: true
          tags: ngrok/ngrok-ingress-controller:latest
