name: Helm Release

on:
  push:
    branches:
      - main
    paths:
      - 'helm/ingress-controller/Chart.yaml'

jobs:
  helm_release:
    if: github.repository == 'ngrok/ngrok-ingress-controller' # Don't run on forks
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.1
        with:
          charts_dir: helm
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
